### ISSUE TITLE
Create user defined encoding functions

### ISSUE THREAD

**Issue by kushagrathisside** [Skillset-analyzers/Students-Skillset-Analysis#8]
#### Following columns require user defined encoding function: *domain, add_skills, achievements* 
These columns contain answers to multiple answer type MCQ. The answers contain all selected options separated by '**;**' . This will be used to split the input and encode it using multiple columns. You may use One Hot Encoding after certain stage.

To solve the issue, first get it assigned to you and then work on the function. In other cases, your PR 'might' not be accepted.

**Comment by Garvit414** [comment]
I want to work on this issue. Please assign it to me.

**Comment by kushagrathisside** [comment]
You can work on it now.
